apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: wajdi1999/auth-api
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: my-app
spec:
  selector:
    app: auth-api
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
