apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: wajdi1999/users-api
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: my-app
spec:
  selector:
    app: users-api
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP
